<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
	<Version>1.0.3</Version>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<AssemblyName>SerialPort.StepPlugin</AssemblyName>
		<RootNamespace>SerialPort</RootNamespace>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<OutputPath>..\..\..\xTestPlatform\xTestPlatform\bin\$(Configuration)\$(TargetFramework)\win-x64\Plugins\SerialPort\</OutputPath>
		<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MessagePack" Version="3.1.7" />
		<PackageReference Include="System.IO.Ports" Version="8.0.0" />
		<PackageReference Include="xTestPlatform.StepEditor.SDK" Version="1.2.1" />
	</ItemGroup>

</Project>
