<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<UseWPF>true</UseWPF>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>SerialPort.StepPlugin.UI</AssemblyName>
	<RootNamespace>SerialPortPlugin.UI</RootNamespace>
	<OutputPath>..\..\..\xTestPlatform\xTestPlatform\bin\$(Configuration)\$(TargetFramework)\win-x64\Plugins\SerialPort\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="MessagePack" Version="3.1.7" />
	<PackageReference Include="Syncfusion.Themes.Windows11Light.WPF" Version="32.1.25" />
	<PackageReference Include="Syncfusion.SfSkinManager.WPF" Version="32.1.25" />
	<PackageReference Include="Syncfusion.Tools.WPF" Version="32.1.25" />
	<PackageReference Include="Syncfusion.SfInput.WPF" Version="32.1.25" />
	<PackageReference Include="xTestPlatform.StepEditor.SDK" Version="1.0.13" />
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\SerialPortPlugin\SerialPortPlugin.csproj" />
  </ItemGroup>

</Project>
