<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableDefaultPageItems>false</EnableDefaultPageItems>
    <AssemblyName>UdpCommunication.StepPlugin.UI</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OutputPath Condition="'$(xTestPlatformAppDir)' != ''">$(xTestPlatformAppDir)\Plugins\UdpCommunication\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UdpCommunicationStepPlugin\UdpCommunicationStepPlugin.csproj" />
    <PackageReference Include="xTestPlatform.StepEditor.SDK" Version="1.0.14" />
    <PackageReference Include="Syncfusion.Tools.WPF" Version="34.1.32" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\UdpCommunicationStepPlugin\Editor\**\*.cs" Link="Editor\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\UdpCommunicationStepPlugin\View\**\*.xaml.cs" Link="View\%(RecursiveDir)%(Filename)%(Extension)" />
    <Compile Include="..\UdpCommunicationStepPlugin\ViewModels\**\*.cs" Link="ViewModels\%(RecursiveDir)%(Filename)%(Extension)" />
    <Page Include="..\UdpCommunicationStepPlugin\View\**\*.xaml" Link="View\%(RecursiveDir)%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
