<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>UdpCommunication.StepPlugin</AssemblyName>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OutputPath Condition="'$(xTestPlatformAppDir)' != ''">$(xTestPlatformAppDir)\Plugins\UdpCommunication\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xTestPlatform.StepEditor.SDK" Version="1.0.14" />
    <PackageReference Include="MessagePack" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Editor\**\*.cs" />
    <Compile Remove="View\**\*.cs" />
    <Compile Remove="ViewModels\**\*.cs" />
    <Page Remove="View\**\*.xaml" />
  </ItemGroup>
</Project>
