<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Version>1.0.3</Version>
	<TargetFramework>net8.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>Modbus.StepPlugin</AssemblyName>
	<RootNamespace>Modbus</RootNamespace>
	<RuntimeIdentifier>win-x64</RuntimeIdentifier>
	<SelfContained>false</SelfContained>
	<AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<OutputPath>..\..\..\xTestPlatform\xTestPlatform\bin\$(Configuration)\$(TargetFramework)\win-x64\Plugins\Modbus\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="MessagePack" Version="3.1.7" />
	<PackageReference Include="xTestPlatform.StepEditor.SDK" Version="1.2.1" />
	<PackageReference Include="NModbus" Version="3.0.81" />
	<PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>

</Project>
