<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Version>1.0.28</Version>
	<TargetFramework>net8.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<UseWPF>true</UseWPF>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>CAN.StepPlugin.UI</AssemblyName>
	<RootNamespace>CAN.UI</RootNamespace>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<OutputPath>..\..\..\xTestPlatform\xTestPlatform\bin\$(Configuration)\$(TargetFramework)\win-x64\Plugins\CAN\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
	<Resource Include="Resources\Icons\can.png">
	  <CopyToOutputDirectory>Never</CopyToOutputDirectory>
	</Resource>
  </ItemGroup>

  <ItemGroup>
	<ProjectReference Include="..\CanPlugin\CanPlugin.csproj" />
	<PackageReference Include="xTestPlatform.StepEditor.SDK" />
	<PackageReference Include="MessagePack" />
	<PackageReference Include="CommunityToolkit.Mvvm" />
	<PackageReference Include="AvalonEdit" />
	<PackageReference Include="Syncfusion.Themes.Windows11Light.WPF" />
	<PackageReference Include="Syncfusion.SfSkinManager.WPF" />
	<PackageReference Include="Syncfusion.Tools.WPF" />
  </ItemGroup>

</Project>
