<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Version>1.0.19</Version>
	<TargetFramework>net8.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>Ethernet.StepPlugin</AssemblyName>
	<RootNamespace>Ethernet</RootNamespace>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<OutputPath>..\..\..\xTestPlatform\xTestPlatform\bin\$(Configuration)\$(TargetFramework)\win-x64\Plugins\Ethernet\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="MessagePack" />
	<PackageReference Include="xTestPlatform.StepEditor.SDK" />
  </ItemGroup>

</Project>
