<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<Version>1.0.21</Version>
	<TargetFramework>net8.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>LIN.StepPlugin</AssemblyName>
	<RootNamespace>LIN</RootNamespace>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<OutputPath>..\..\..\xTestPlatform\xTestPlatform\bin\$(Configuration)\$(TargetFramework)\win-x64\Plugins\LIN\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="MessagePack" Version="3.1.7" />
	<PackageReference Include="xTestPlatform.StepEditor.SDK" Version="1.2.3" />
  </ItemGroup>

</Project>
