<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0-windows</TargetFramework>
	<Nullable>enable</Nullable>
	<ImplicitUsings>enable</ImplicitUsings>
	<AssemblyName>VISA.StepPlugin</AssemblyName>
	<RootNamespace>VISA</RootNamespace>
	<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	<OutputPath>..\..\..\xTestPlatform\xTestPlatform\bin\$(Configuration)\$(TargetFramework)\win-x64\Plugins\VISA\</OutputPath>
	<AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="MessagePack" Version="3.1.7" />
	<PackageReference Include="xTestPlatform.StepEditor.SDK" Version="1.1.1" />
	<PackageReference Include="IviFoundation.Visa" Version="8.0.2" />
  </ItemGroup>

</Project>
